//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XboxGamesApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string Description { get; set; }
        public string Developer { get; set; }
        public Nullable<int> GenreId { get; set; }
        public byte[] Image { get; set; }
        public string ImageUrl { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> RatingId { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Rating Rating { get; set; }
    }
}
